"""DATS — Strategy Engine Pydantic v2 Schemas.

Defines all data models used by the strategy engine: strategy configurations,
signals, backtest results, trade records, performance metrics, and A/B testing.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

import pandas as pd
from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class StrategyType(str, Enum):
    """Classification of trading strategies."""

    TREND_FOLLOWING = "trend_following"
    MEAN_REVERSION = "mean_reversion"
    MOMENTUM = "momentum"
    BREAKOUT = "breakout"
    STATISTICAL_ARBITRAGE = "statistical_arbitrage"


class SignalDirection(str, Enum):
    """Possible signal directions."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


# ---------------------------------------------------------------------------
# Strategy Configuration
# ---------------------------------------------------------------------------


class StrategyConfig(BaseModel):
    """Configuration for a trading strategy instance."""

    strategy_type: StrategyType = Field(
        ..., description="Strategy classification."
    )
    symbol: str = Field(..., description="Trading symbol, e.g. 'SOL/USDC'.")
    parameters: dict[str, float] = Field(
        default_factory=dict, description="Tunable strategy parameters."
    )
    enabled: bool = Field(default=True, description="Whether the strategy is active.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of configuration creation.",
    )

    @field_validator("timestamp", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value


# ---------------------------------------------------------------------------
# Strategy Signal
# ---------------------------------------------------------------------------


class StrategySignal(BaseModel):
    """A trading signal generated by a strategy.

    Extends the base Signal concept with strategy-specific fields.
    """

    symbol: str = Field(..., description="Trading symbol, e.g. 'SOL/USDC'.")
    direction: SignalDirection = Field(..., description="BUY, SELL, or HOLD.")
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence score from 0.0 to 1.0."
    )
    reason: str = Field(default="", description="Human-readable reasoning.")
    features_used: dict[str, float | None] = Field(
        default_factory=dict,
        description="Feature name to value mapping used for the signal.",
    )
    strategy_name: str = Field(..., description="Name of the generating strategy.")
    parameters_used: dict[str, float] = Field(
        default_factory=dict,
        description="Parameters used when generating the signal.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of signal generation.",
    )

    @field_validator("timestamp", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value

    @field_validator("confidence")
    @classmethod
    def _confidence_in_range(cls, value: float) -> float:
        if not 0.0 <= value <= 1.0:
            raise ValueError("confidence must be between 0.0 and 1.0")
        return value


# ---------------------------------------------------------------------------
# Trade Record
# ---------------------------------------------------------------------------


class TradeRecord(BaseModel):
    """A single trade executed by the backtesting engine."""

    entry_time: datetime = Field(..., description="Entry timestamp.")
    exit_time: datetime | None = Field(
        default=None, description="Exit timestamp (None if still open)."
    )
    entry_price: float = Field(..., gt=0, description="Entry price.")
    exit_price: float | None = Field(
        default=None, description="Exit price (None if still open)."
    )
    size: float = Field(..., gt=0, description="Position size.")
    direction: Literal["long", "short"] = Field(..., description="Trade direction.")
    pnl: float = Field(default=0.0, description="Realized P&L.")
    fees: float = Field(default=0.0, description="Total fees paid.")
    signal_id: str = Field(default="", description="ID of the triggering signal.")

    @field_validator("entry_time", mode="before")
    @classmethod
    def _ensure_utc_entry(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value

    @field_validator("exit_time", mode="before")
    @classmethod
    def _ensure_utc_exit(cls, value: datetime | str | None) -> datetime | None:
        if value is None:
            return None
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value

    def is_open(self) -> bool:
        """Return True if the trade is still open."""
        return self.exit_time is None


# ---------------------------------------------------------------------------
# Performance Metrics
# ---------------------------------------------------------------------------


class PerformanceMetrics(BaseModel):
    """Comprehensive performance metrics for a strategy."""

    total_return: float = Field(
        default=0.0, description="Total return as a decimal (e.g. 0.15 = 15%)."
    )
    annualized_return: float = Field(
        default=0.0, description="Annualized return as a decimal."
    )
    sharpe_ratio: float = Field(default=0.0, description="Sharpe ratio.")
    sortino_ratio: float = Field(default=0.0, description="Sortino ratio.")
    max_drawdown: float = Field(
        default=0.0, description="Maximum drawdown as a positive decimal."
    )
    max_drawdown_duration: int = Field(
        default=0, description="Max drawdown duration in bars."
    )
    calmar_ratio: float = Field(
        default=0.0, description="Calmar ratio (annualized return / max drawdown)."
    )
    win_rate: float = Field(
        default=0.0, ge=0.0, le=1.0, description="Win rate as a decimal."
    )
    profit_factor: float = Field(
        default=0.0, description="Gross profit / gross loss."
    )
    avg_win: float = Field(default=0.0, description="Average winning trade return.")
    avg_loss: float = Field(default=0.0, description="Average losing trade return.")
    expectancy: float = Field(
        default=0.0, description="Expected return per trade."
    )
    num_trades: int = Field(default=0, ge=0, description="Total number of trades.")
    avg_holding_period: float = Field(
        default=0.0, description="Average holding period in bars."
    )
    volatility: float = Field(
        default=0.0, description="Annualized volatility of returns."
    )
    skewness: float = Field(default=0.0, description="Skewness of returns.")
    kurtosis: float = Field(default=0.0, description="Excess kurtosis of returns.")

    @field_validator("win_rate")
    @classmethod
    def _win_rate_in_range(cls, value: float) -> float:
        if not 0.0 <= value <= 1.0:
            raise ValueError("win_rate must be between 0.0 and 1.0")
        return value


# ---------------------------------------------------------------------------
# Backtest Result
# ---------------------------------------------------------------------------


class BacktestResult(BaseModel):
    """Complete result from a backtest run."""

    strategy_name: str = Field(..., description="Name of the strategy backtested.")
    symbol: str = Field(..., description="Trading symbol.")
    start_date: datetime = Field(..., description="Backtest start date.")
    end_date: datetime = Field(..., description="Backtest end date.")
    total_return: float = Field(default=0.0, description="Total return as decimal.")
    sharpe_ratio: float = Field(default=0.0, description="Sharpe ratio.")
    max_drawdown: float = Field(
        default=0.0, description="Maximum drawdown as positive decimal."
    )
    win_rate: float = Field(default=0.0, description="Win rate as decimal.")
    num_trades: int = Field(default=0, description="Total number of trades.")
    avg_trade_return: float = Field(
        default=0.0, description="Average return per trade."
    )
    profit_factor: float = Field(default=0.0, description="Profit factor.")
    equity_curve: list[float] = Field(
        default_factory=list, description="Equity curve values over time."
    )
    trades: list[TradeRecord] = Field(
        default_factory=list, description="All trades executed."
    )
    parameters: dict[str, float] = Field(
        default_factory=dict, description="Parameters used for the backtest."
    )
    metrics: PerformanceMetrics = Field(
        default_factory=PerformanceMetrics,
        description="Comprehensive performance metrics.",
    )

    @field_validator("start_date", "end_date", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value

    def to_dataframe(self) -> pd.DataFrame:
        """Convert trades to a pandas DataFrame for analysis."""
        if not self.trades:
            return pd.DataFrame()
        data = []
        for t in self.trades:
            data.append({
                "entry_time": t.entry_time,
                "exit_time": t.exit_time,
                "entry_price": t.entry_price,
                "exit_price": t.exit_price,
                "size": t.size,
                "direction": t.direction,
                "pnl": t.pnl,
                "fees": t.fees,
                "signal_id": t.signal_id,
            })
        return pd.DataFrame(data)


# ---------------------------------------------------------------------------
# A/B Testing
# ---------------------------------------------------------------------------


class ABTest(BaseModel):
    """Configuration for an A/B test between two strategies."""

    name: str = Field(..., description="Test name / identifier.")
    strategy_a_name: str = Field(..., description="Name of strategy A.")
    strategy_b_name: str = Field(..., description="Name of strategy B.")
    confidence_level: float = Field(
        default=0.95, ge=0.0, le=1.0, description="Statistical confidence level."
    )
    status: Literal["pending", "running", "completed"] = Field(
        default="pending", description="Test status."
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Test creation timestamp.",
    )

    @field_validator("created_at", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value


class ABTestResult(BaseModel):
    """Result of an A/B test between two strategies."""

    test_name: str = Field(..., description="Test name / identifier.")
    strategy_a_name: str = Field(..., description="Name of strategy A.")
    strategy_b_name: str = Field(..., description="Name of strategy B.")
    strategy_a_metrics: PerformanceMetrics = Field(
        ..., description="Performance metrics for strategy A."
    )
    strategy_b_metrics: PerformanceMetrics = Field(
        ..., description="Performance metrics for strategy B."
    )
    winner: Literal["A", "B", "tie"] = Field(
        ..., description="Winning strategy or tie."
    )
    p_value: float = Field(
        ..., ge=0.0, le=1.0, description="Statistical significance p-value."
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence level used."
    )
    recommendation: str = Field(
        default="", description="Human-readable recommendation."
    )


# ---------------------------------------------------------------------------
# Hot-swap State
# ---------------------------------------------------------------------------


class StrategyState(BaseModel):
    """Serializable state of a strategy for hot-swap persistence."""

    name: str = Field(..., description="Strategy name.")
    strategy_type: StrategyType = Field(..., description="Strategy classification.")
    parameters: dict[str, float] = Field(
        default_factory=dict, description="Current parameters."
    )
    enabled: bool = Field(default=True, description="Whether enabled.")
    state_data: dict[str, Any] = Field(
        default_factory=dict, description="Strategy-specific state data."
    )
    last_updated: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last state update timestamp.",
    )

    @field_validator("last_updated", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value
