"""DATS — Agent Framework Pydantic v2 Schemas.

Defines the core data models used by all agents in the multi-agent
trading system: agent state, messages, signals, decisions, and health.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator

from trading.schemas import SignalDirection


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class AgentState(str, Enum):
    """Lifecycle states for an agent."""

    INITIALIZING = "initializing"
    IDLE = "idle"
    THINKING = "thinking"
    ACTING = "acting"
    ERROR = "error"
    SHUTDOWN = "shutdown"


# SignalDirection imported from trading.schemas


class DecisionType(str, Enum):
    """Types of agent decisions."""

    SIGNAL = "signal"
    RISK_ALERT = "risk_alert"
    ORDER = "order"
    COORDINATION = "coordination"
    KILL_SWITCH = "kill_switch"
    NOOP = "noop"


class MessageType(str, Enum):
    """Inter-agent message types."""

    SIGNAL = "signal"
    RISK_ALERT = "risk_alert"
    ORDER_REQUEST = "order_request"
    ORDER_RESPONSE = "order_response"
    HEALTH_CHECK = "health_check"
    COMMAND = "command"
    STATUS = "status"
    KILL_SWITCH = "kill_switch"


# ---------------------------------------------------------------------------
# Core models
# ---------------------------------------------------------------------------


class AgentMessage(BaseModel):
    """An inter-agent message sent via the message bus."""

    from_agent: str = Field(..., description="Sender agent ID.")
    to_agent: str | None = Field(default=None, description="Target agent ID (None = broadcast).")
    message_type: str = Field(..., description="Message type.")
    payload: dict[str, Any] = Field(default_factory=dict, description="Message payload.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp.",
    )

    @field_validator("timestamp", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value


class Signal(BaseModel):
    """A trading signal generated by a strategy agent."""

    symbol: str = Field(..., description="Trading symbol, e.g. 'SOL/USDC'.")
    direction: SignalDirection = Field(..., description="BUY, SELL, or HOLD.")
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score from 0.0 to 1.0.",
    )
    reason: str = Field(default="", description="Human-readable reasoning.")
    features_used: dict[str, float | None] = Field(
        default_factory=dict,
        description="Feature name → value mapping used for the signal.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of signal generation.",
    )
    agent_id: str = Field(default="", description="Agent that generated the signal.")
    strategy: str = Field(default="", description="Strategy rule used.")

    @field_validator("timestamp", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value

    @field_validator("confidence")
    @classmethod
    def _confidence_in_range(cls, value: float) -> float:
        if not 0.0 <= value <= 1.0:
            raise ValueError("confidence must be between 0.0 and 1.0")
        return value


class AgentDecision(BaseModel):
    """An agent's decision after the THINK phase."""

    agent_id: str = Field(..., description="Agent that made the decision.")
    decision_type: DecisionType = Field(..., description="Type of decision.")
    payload: dict[str, Any] = Field(default_factory=dict, description="Decision payload.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp.",
    )
    reasoning: str = Field(default="", description="Chain-of-thought reasoning.")
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Confidence in the decision.",
    )

    @field_validator("timestamp", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value


class AgentHealth(BaseModel):
    """Health status of an agent."""

    agent_id: str = Field(..., description="Agent identifier.")
    state: AgentState = Field(..., description="Current lifecycle state.")
    last_active: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last activity timestamp.",
    )
    error_count: int = Field(default=0, ge=0, description="Cumulative error count.")
    tasks_completed: int = Field(default=0, ge=0, description="Tasks completed successfully.")
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Agent-specific metadata.",
    )

    @field_validator("last_active", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value


class RiskAssessment(BaseModel):
    """Risk assessment produced by the RiskAgent."""

    portfolio_value: float = Field(default=0.0, description="Current portfolio value in USD.")
    total_exposure: float = Field(default=0.0, description="Total exposure.")
    max_position_size: float = Field(default=0.0, description="Max position limit.")
    current_drawdown: float = Field(default=0.0, description="Current drawdown %.")
    max_drawdown_limit: float = Field(default=0.0, description="Max drawdown limit %.")
    var_estimate: float = Field(default=0.0, description="Estimated daily VaR.")
    var_limit: float = Field(default=0.0, description="Daily VaR limit.")
    exposure_by_asset: dict[str, float] = Field(
        default_factory=dict,
        description="Exposure per asset.",
    )
    risk_level: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"] = Field(
        default="LOW",
        description="Overall risk level.",
    )
    breached_limits: list[str] = Field(
        default_factory=list,
        description="List of breached limit names.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp.",
    )

    @field_validator("timestamp", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value


class OrderDetails(BaseModel):
    """Order details for execution."""

    symbol: str = Field(..., description="Trading symbol.")
    side: Literal["buy", "sell"] = Field(..., description="Order side.")
    size: float = Field(..., gt=0, description="Order size.")
    order_type: Literal["market", "limit"] = Field(default="market", description="Order type.")
    price: float | None = Field(default=None, description="Limit price (for limit orders).")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0, description="Signal confidence.")
    reason: str = Field(default="", description="Reason for the order.")
    execution_mode: Literal["PAPER_TRADE", "LIVE_DRY_RUN", "LIVE_ARMED"] = Field(
        default="PAPER_TRADE",
        description="Execution mode.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp.",
    )

    @field_validator("timestamp", mode="before")
    @classmethod
    def _ensure_utc(cls, value: datetime | str) -> datetime:
        if isinstance(value, str):
            value = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value
